# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c3a149bac29a1893e43b84b0ba94f0d9775d15901f5179bdd514654c7d2b2c2a9f18e95117556b58989b72e484f168c74ad422b075c0d64f19ca1e279122be

test:
  secret_key_base: 6768ab996373b7b83e8ab75f305095190ba97548b3ec73509789b858befd28fb58000e2ba322b541c8808171f015ae510e6a340d2d3275aca90e73e8bfbb4a4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
